services:
    # We want this docker container to run an RStudio instance
    rstudio: 
        build: .
        # Tag the built Dockerfile this name
        image: aallyn/dockertesting_aja
        # Ports, not entirely sure what this does?
        ports: 
            - "8787:8787"
        # Mapping the connections between things on our local system to the docker container
        volumes:
        - ./scratch/aja/data:/data
    